name: Bump Version on Merge to Master

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # needed for pushing changes
          fetch-depth: 0

      - name: Set up Node.js (for jq/json editing)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Bump patch version
        id: bump
        run: |
          FILE=src/versioning
          VERSION=$(jq -r '.version' $FILE)
          BASE=$(echo $VERSION | cut -d. -f1-2)
          PATCH=$(echo $VERSION | cut -d. -f3)
          NEW_PATCH=$((PATCH+1))
          NEW_VERSION="$BASE.$NEW_PATCH"

          echo "New version: $NEW_VERSION"
          jq --arg v "$NEW_VERSION" '.version=$v' $FILE > tmp && mv tmp $FILE

          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add src/versioning
          git commit -m "Bump version to ${{ steps.bump.outputs.version }}"
          git push
